-- Baseline: the production schema as of 2026-10-03, taken with
--   pg_dump --schema-only --no-owner --no-privileges   (server: PostgreSQL 16.14)
-- Only pg_dump session settings (SET ..., set_config, \restrict) were removed; the DDL is verbatim.
--
-- Production already has these tables: Flyway marks it as baselined at version 1
-- (spring.flyway.baseline-on-migrate) and never runs this file there.
-- It runs only on empty databases (local dev, tests, a rebuilt environment).
--
-- Known leftovers from the ddl-auto=update era, kept so this file matches production exactly:
--   pack.basic_price, pack.start_time, schedulings.happened (no entity maps them).

CREATE TABLE public.customer (
    id bigint NOT NULL,
    cpf character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    number character varying(255) NOT NULL,
    address character varying(255),
    customer_obs character varying(1000)
);

ALTER TABLE public.customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.pack (
    id bigint NOT NULL,
    basic_price numeric(38,2),
    frequencia character varying(255),
    name character varying(255),
    start_time timestamp(6) without time zone
);

ALTER TABLE public.pack ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pack_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.pack_protocol (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    package_id bigint NOT NULL,
    protocol_id bigint NOT NULL
);

ALTER TABLE public.pack_protocol ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pack_protocol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.pet (
    id bigint NOT NULL,
    age double precision NOT NULL,
    name character varying(255) NOT NULL,
    obs character varying(1000),
    race character varying(255) NOT NULL,
    species character varying(255) NOT NULL,
    customer_id bigint NOT NULL,
    allergy character varying(255),
    coat_type character varying(255),
    dewormed boolean,
    dewormed_date date,
    health_issues character varying(255),
    rabie_vaccination boolean,
    rabie_vaccination_date date,
    v10_vaccination boolean,
    v10_vaccination_date date,
    weight real,
    pack_id bigint,
    package_price numeric(38,2),
    birthday date,
    CONSTRAINT pet_coat_type_check CHECK (((coat_type)::text = ANY (ARRAY[('SHORT'::character varying)::text, ('MEDIUM'::character varying)::text, ('LONG'::character varying)::text, ('CURLY'::character varying)::text])))
);

ALTER TABLE public.pet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.product_variants (
    id bigint NOT NULL,
    color character varying(255),
    cost_price numeric(10,2),
    current_stock_qty numeric(10,3),
    sale_price numeric(10,2),
    size character varying(255),
    sku character varying(35) NOT NULL,
    status character varying(255),
    product_id bigint NOT NULL,
    CONSTRAINT product_variants_status_check CHECK (((status)::text = ANY (ARRAY[('ACTIVE'::character varying)::text, ('INACTIVE'::character varying)::text, ('ON_DEMAND'::character varying)::text, ('DISCONTINUED'::character varying)::text])))
);

ALTER TABLE public.product_variants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_variants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.products (
    id bigint NOT NULL,
    animal_target character varying(255) NOT NULL,
    barcode character varying(20),
    brand character varying(255),
    category character varying(255) NOT NULL,
    cost_price numeric(10,2) NOT NULL,
    created_at timestamp(6) without time zone,
    current_stock_qty numeric(10,3),
    loose boolean NOT NULL,
    min_stock_qty numeric(10,3),
    name character varying(255) NOT NULL,
    ncm character varying(10),
    sale_price numeric(10,2) NOT NULL,
    shelf_location character varying(255),
    sku character varying(30) NOT NULL,
    status character varying(255) NOT NULL,
    unit character varying(10) NOT NULL,
    updated_at timestamp(6) without time zone,
    supplier_id bigint,
    CONSTRAINT products_animal_target_check CHECK (((animal_target)::text = ANY (ARRAY[('DOG'::character varying)::text, ('CAT'::character varying)::text, ('BIRD'::character varying)::text, ('FISH'::character varying)::text, ('RODENT'::character varying)::text, ('REPTILE'::character varying)::text, ('ALL'::character varying)::text]))),
    CONSTRAINT products_category_check CHECK (((category)::text = ANY (ARRAY[('ROU'::character varying)::text, ('ACE'::character varying)::text, ('BRI'::character varying)::text, ('CAM'::character varying)::text, ('HIG'::character varying)::text, ('ALI'::character varying)::text, ('OUT'::character varying)::text]))),
    CONSTRAINT products_status_check CHECK (((status)::text = ANY (ARRAY[('ACTIVE'::character varying)::text, ('INACTIVE'::character varying)::text, ('ON_DEMAND'::character varying)::text, ('DISCONTINUED'::character varying)::text])))
);

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.protocols (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255)
);

ALTER TABLE public.protocols ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.protocols_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.receipt_items (
    id bigint NOT NULL,
    description character varying(255) NOT NULL,
    product_id bigint,
    product_sku character varying(255),
    quantity numeric(10,3) NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    receipt_id bigint NOT NULL
);

ALTER TABLE public.receipt_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.receipt_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.receipts (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    customer_id bigint,
    customer_name character varying(255),
    discount numeric(10,2) NOT NULL,
    number character varying(255) NOT NULL,
    observations character varying(500),
    pet_id bigint,
    pet_name character varying(255),
    scheduling_id bigint,
    status character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT receipts_status_check CHECK (((status)::text = ANY (ARRAY[('PENDING'::character varying)::text, ('PAID'::character varying)::text, ('CANCELLED'::character varying)::text]))),
    CONSTRAINT receipts_type_check CHECK (((type)::text = ANY (ARRAY[('PRODUCT'::character varying)::text, ('SERVICE'::character varying)::text])))
);

ALTER TABLE public.receipts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.receipts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.scheduling_protocols (
    id bigint NOT NULL,
    protocol_id bigint NOT NULL,
    protocol_name character varying(255) NOT NULL,
    protocol_price numeric(38,2),
    scheduling_id bigint NOT NULL
);

ALTER TABLE public.scheduling_protocols ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scheduling_protocols_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.schedulings (
    id bigint NOT NULL,
    customer_id bigint NOT NULL,
    customer_name character varying(255),
    duration integer,
    is_package boolean,
    pet_id bigint,
    pet_name character varying(255),
    happened boolean,
    observations character varying(255),
    "time" timestamp(6) without time zone,
    intercepted boolean,
    schedule_status character varying(255),
    pack_id bigint,
    pack_cycle integer,
    price numeric(38,2),
    CONSTRAINT schedulings_schedule_status_check CHECK (((schedule_status)::text = ANY (ARRAY[('CONFIRMED'::character varying)::text, ('HAPPENED'::character varying)::text, ('CANCELED'::character varying)::text, ('SCHEDULED'::character varying)::text])))
);

ALTER TABLE public.schedulings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedulings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.suppliers (
    id bigint NOT NULL,
    active boolean NOT NULL,
    avg_lead_time_days integer,
    cnpj character varying(18),
    code character varying(20) NOT NULL,
    contact_name character varying(255),
    created_at timestamp(6) without time zone,
    email character varying(255),
    min_order_qty integer,
    name character varying(255) NOT NULL,
    phone character varying(255),
    updated_at timestamp(6) without time zone
);

ALTER TABLE public.suppliers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suppliers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.pack
    ADD CONSTRAINT pack_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.pack_protocol
    ADD CONSTRAINT pack_protocol_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.pet
    ADD CONSTRAINT pet_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.product_variants
    ADD CONSTRAINT product_variants_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.protocols
    ADD CONSTRAINT protocols_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.receipt_items
    ADD CONSTRAINT receipt_items_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.receipts
    ADD CONSTRAINT receipts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.scheduling_protocols
    ADD CONSTRAINT scheduling_protocols_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.schedulings
    ADD CONSTRAINT schedulings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.suppliers
    ADD CONSTRAINT suppliers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.receipts
    ADD CONSTRAINT uk8bseq5w9g355l73wd5fnmfyhj UNIQUE (number);

ALTER TABLE ONLY public.suppliers
    ADD CONSTRAINT uk8kh5crh75ye2imfi5yv37p61o UNIQUE (code);

ALTER TABLE ONLY public.products
    ADD CONSTRAINT ukfhmd06dsmj6k0n90swsh8ie9g UNIQUE (sku);

ALTER TABLE ONLY public.product_variants
    ADD CONSTRAINT ukq935p2d1pbjm39n0063ghnfgn UNIQUE (sku);

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fk6i174ixi9087gcvvut45em7fd FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id);

ALTER TABLE ONLY public.pack_protocol
    ADD CONSTRAINT fkcbkfgijkvhmj8g99jeki8c3l5 FOREIGN KEY (protocol_id) REFERENCES public.protocols(id);

ALTER TABLE ONLY public.receipt_items
    ADD CONSTRAINT fkmyfhuc1y0sjqe2geey8jx9nc2 FOREIGN KEY (receipt_id) REFERENCES public.receipts(id);

ALTER TABLE ONLY public.product_variants
    ADD CONSTRAINT fkosqitn4s405cynmhb87lkvuau FOREIGN KEY (product_id) REFERENCES public.products(id);

ALTER TABLE ONLY public.scheduling_protocols
    ADD CONSTRAINT fkqb4kmb70qn77597qqm9876gep FOREIGN KEY (scheduling_id) REFERENCES public.schedulings(id);

ALTER TABLE ONLY public.pack_protocol
    ADD CONSTRAINT fkqgrf4a50du12j2vjh3cdaqkhw FOREIGN KEY (package_id) REFERENCES public.pack(id);

ALTER TABLE ONLY public.pet
    ADD CONSTRAINT fkt742r2fu4c3i9sn6a8kv0k746 FOREIGN KEY (customer_id) REFERENCES public.customer(id);

