-- Phase 1 — Identity (2026-10-05). Real user accounts replace the single app.admin login.
--
-- Decisions (see SAAS-ROADMAP.md §4):
--   * login by e-mail; e-mail unique case-insensitively (globally — Phase 2 adds memberships per shop);
--   * the role lives on the user for now; Phase 2 moves it to memberships(user, tenant, role);
--   * no e-mail service: an OWNER/ADMIN sets a temporary password (must_change_password = true),
--     so the roadmap's password_reset_tokens table is not created;
--   * token_version: bumping it invalidates every access token of that user at once.
--
-- In production this runs as petshop_migrator; default privileges give app_user read/write access.

CREATE TABLE users (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id            uuid         NOT NULL DEFAULT gen_random_uuid(),
    email                varchar(255) NOT NULL,
    password_hash        varchar(100) NOT NULL,
    name                 varchar(255) NOT NULL,
    role                 varchar(20)  NOT NULL CHECK (role IN ('OWNER', 'ADMIN', 'STAFF', 'VIEWER')),
    status               varchar(20)  NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'DISABLED')),
    must_change_password boolean      NOT NULL DEFAULT false,
    token_version        integer      NOT NULL DEFAULT 0,
    last_login_at        timestamp(6) with time zone,
    created_at           timestamp(6) with time zone NOT NULL DEFAULT now(),
    updated_at           timestamp(6) with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_users_email    ON users (lower(email));
CREATE UNIQUE INDEX ux_users_publicid ON users (public_id);

-- Refresh tokens: only a SHA-256 hash is stored; the raw value lives in an httpOnly cookie.
-- Each refresh rotates the token (replaced_by); presenting a revoked token again = theft → all revoked.
CREATE TABLE refresh_tokens (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash  varchar(64)  NOT NULL,
    expires_at  timestamp(6) with time zone NOT NULL,
    revoked_at  timestamp(6) with time zone,
    replaced_by bigint       REFERENCES refresh_tokens (id),
    ip          varchar(45),
    user_agent  varchar(255),
    created_at  timestamp(6) with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_refresh_hash ON refresh_tokens (token_hash);
CREATE INDEX ix_refresh_user_active ON refresh_tokens (user_id) WHERE revoked_at IS NULL;
